site_name: Modelo Visão Computacional
nav:
  - Bem vindo a Marte: index.md
  - Ambiente: ambiente.md
  - Imagens de Treino: imagens_treino.md
  - Tratamento dos dados: notebook_estudo.ipynb
plugins:
  - mkdocs-jupyter
theme:
    name: 'material'